### ISSUE TITLE
ios crash

### ISSUE THREAD

**Issue by jcharbo** [Ziggeo/ReactNativeDemo#1]
Hi, I'm trying to build this project in xcode and it is not working.  I cloned the repo and opened xcode and hit build.  I got the attached errors.  Please advise.
![screen shot 2017-08-30 at 9 05 33 am](https://user-images.githubusercontent.com/6372919/29876498-8e7c0e54-8d62-11e7-9682-0ba21faa66e3.png)

**Comment by alexyats** [comment]
the SDK included with demo is not universal and built for real device only, so please use Generic or real device as the compilation target
