### ISSUE TITLE
ios demo  error

### ISSUE THREAD

**Issue by TrustTheBoy** [Ziggeo/ReactNativeDemo#11]
![image](https://user-images.githubusercontent.com/20201085/65830254-6b2a5980-e2e0-11e9-92df-4edee3f494e9.png)

**Comment by ntshrocha** [comment]
Hi @TrustTheBoy, it looks like you're using an outdated version of Ziggeo.framework. Did you follow the steps to update it? This is what you need to do:

1. Download Ziggeo.framework from Ziggeo-Client-SDK repository: https://github.com/Ziggeo/iOS-Client-SDK/tree/master/Ziggeo/Output/
 You should use the **universal** framework during development, and then switch to the other one when building for the App Store.
2. Open the iOS project in XCode and add the Ziggeo.framework into embedded and linked frameworks at the project settings.
3. Override the original Ziggeo.framework folder inside the project.

Please try following these steps and let us know if it helps.

**Comment by oliverfriedmann** [comment]
Closing as it seems stale. Feel free to re-open.
