### ISSUE TITLE
Error running demo on Android

### ISSUE THREAD

**Issue by dancomanlive** [Ziggeo/ReactNativeDemo#6]
![screen shot 2017-11-23 at 11 24 46 am](https://user-images.githubusercontent.com/16872821/33157981-2456c786-d041-11e7-8114-edf43562319f.png)

**Comment by 3akat** [comment]
Hi @dancomanlive, 
Please, take a look at the latest version. Should be fixed.

**Comment by dancomanlive** [comment]
Hi @3akat 
What version are you referring to? ReactNative Demo, ZiggeoRN SDK or Android SDK ?

**Comment by dancomanlive** [comment]
Hi @3akat 

Now I am getting Error:Execution failed for task ':react-native-ziggeo-library:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

opening new issue

**Comment by dancomanlive** [comment]
The issue is occurring again when building :(

**Comment by 3akat** [comment]
Fixed.
