### ISSUE TITLE
Error:Execution failed for task ':react-native-ziggeo-library:compileDebugJavaWithJavac'. > Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by dancomanlive** [Ziggeo/ReactNativeDemo#7]
When building in Android Studio. Running the latest version of everyting - npm outdated shows no results.

**Comment by 3akat** [comment]
@dancomanlive, can you please put `compiler error output` here?

**Comment by 3akat** [comment]
@dancomanlive it looks like a pretty common issue.
https://github.com/facebook/react-native/issues/3437
`cd android & ./gradlew clean` - should help

**Comment by 3akat** [comment]
There was a wrong info in README. Fixed.
